server {
    #port to listen to
    listen 443;
    # the request should be coming from this url in order to execute this block
    server_name webserve.42.fr;
    #error pages to serve in case of an error. 404: server is works but file requested not found 502: server tried to execute what it is asked of but crashed
    error_page 404 404.html;
    error_page 502 502.html;
    #set the limit a client can upload to the server to prevent crashes
    client_max_body_size 10M; 

    location / {
        #root get always added its the path u go look in example i want ping1.png u will look for it in var/html
        root var/html;
        #file to look for when a file is requested
        index index.html;
        #autoindex can be turned on and off. if its on if the client requested a whole directory u serve them a html page with all the files in that dir, if its off u dont
        autoindex on;

    }
}