


server {
    #port to listen to
    listen 80;
    # the request should be coming from this url in order to execute this block
    #error pages to serve in case of an error. 404: server is works but file requested not found 502: server tried to execute what it is asked of but crashed
    error_page 404 404.html;
    error_page 502 502.html;
    #set the limit a client can upload to the server to prevent crashes
    client_max_body_size 10M; 
    #default root and index for the server block
    root www/html;
    index index.html;
    location / {
        #root get always added its the path u go look in into 
        root www/html;
        #file to look for when a file is requested
        index index.html;
        #autoindex can be turned on and off. if its on if the client requested a whole directory u serve them a html page with all the files in that dir, if its off u dont
        autoindex on;
        #we only need to send requests for our static files not modify them or delete them
        allowed_methods GET;
    }
    location /old {
        return 301 /new.html;
    }
    location /uploads {
        #where to read files from
        root www;

        #we can upload request and delete these files
        allowed_methods GET POST DELETE;

        #where to upload files to
        upload_pass www/uploads;
    }
    location /bin-cgi {

        root www;
        allowed_methods GET POST;
        #which program to run scripts with
        cgi_pass .py /usr/bin/python3;
        cgi_pass .php /usr/bin/php-cgi;
    }
}